### ISSUE TITLE
Expose a tm.commit_veto2 api that passes in the exception object.

### ISSUE THREAD

**Issue by mmerickel** [Pylons/pyramid_tm#32]
A fault in `tm.commit_veto` is that it does not let you evaluate the exception object when writing the veto logic. I don't see a good way to do this with the current api so I propose a `tm.commit_veto2` that adds a third parameter to the callback. Both vetos would be used if defined, as an "or" operation. So if either callback wanted to veto, then it would be vetoed.

This is useful for some people who may not want certain exceptions to cancel a transaction (e.g. `HTTPFound`).

**Comment by bpicolo** [comment]
I encountered this similarly, I'd consider it a bug. pyramid expects redirects to be raised exceptions:
http://pyramid-cookbook.readthedocs.org/en/latest/pylons/exceptions.html

If the tween isn't checking the commit veto in these cases it's pretty pointless.

**Comment by bertjwregeer** [comment]
@bpicolo I don't agree with your statement that Pyramid expects redirects to be raised exceptions. The reason you raise an exception for exceptional circumstances is so that you can then modify the response before it being sent onwards.

Returning `HTTPFound()` is perfectly valid, and the right thing to do.

**Comment by bpicolo** [comment]
@bertjwregeer  It's literally built into pyramid. 
https://github.com/Pylons/pyramid/blob/master/pyramid/httpexceptions.py#L302

Saying we're acting upon responses for "exceptional circumstances" is a strange way of putting it because it's the point of this library. There are multiple valid strategies, and pyramid_tm currently only supports one of them.

**Comment by bertjwregeer** [comment]
@bpicolo Yes, they may be listed as exceptions, each and every one of those is a valid response too. As the `pyramid_tm` changelog notes:

> This means it's best to "raise HTTPFound(...)" instead of "return HTTPFound(...)" if you want an HTTP exception to abort the transaction.

Your changes means that if I return an `HTTPNotFound()` which previously would have simply caused the transaction to be committed, it no longer will with your PR, since it is a 400 class error message.

It is well documented in Pyramid that returning an `HTTPException` will simply render it as a response, whereas raising it will instead cause the exception machinery to kick in, and ultimately caught by the default exception view and rendered. `pyramid_tm` inserts itself in between so that it can correctly roll-back the transaction.

**Comment by dstufft** [comment]
This isn't really a "veto" thing, because you veto something that would otherwise pass, it's more like a "should pass anyways" kind of thing, in other words, it takes a failing transaction and makes it passing.

Conceptually I don't have a problem exactly with the idea of a "should pass anyways" hook, the biggest concern I have is that it may be a footgun. Raising an exception means that it's possible a bunch of code gets skipped before it hits the exception handler and it's hard to tell what that code is going to do. This may mean that ultimately transactions end up failing because some bit of code in a tween didn't get run. Is there a use case that isn't http exceptions? If it's just the http exceptions then what's wrong with (as @bertjwregeer pointed out) just returning the httpexception when you want the view to be "successful" and reserve raising for when the view should be considered "unsuccessful"?

**Comment by mmerickel** [comment]
The desire is mainly a pylons-holdover of people wishing to redirect (HTTPFound) via raise. I think we should consider moving the exceptions into pyramid.httpresponses instead of pyramid.httpexceptions or something and consider it more of a documentation problem than anything.

**Comment by dstufft** [comment]
That seems like a reasonable result, especially now that I think more about it and ``return`` vs ``raise`` is a good way to differentiate between success and failure even when the result might be the same. For instance -> You may redirect to a login page for a "failure" and you may redirect to a success message for a "success".

**Comment by mmerickel** [comment]
Okay I think it makes sense to maintain the "raise = abort" semantics until some other use case comes along.
